blank_issues_enabled: false
contact_links:
  - name: ğŸš‘ Help & Support
    url: https://github.com/orgs/OperationCaribbeanSummer/discussions
    about: Please use the community forum for questions
  - name: ğŸ’¡ Features & Ideas
    url: https://github.com/orgs/OperationCaribbeanSummer/discussions/categories/ideas
    about: Please vote for & post new ideas in the the forum
  - name: ğŸ“– Documentation
    url: https://OperationCaribbeanSummer.github.io/.github
    about: Tutorials & reference guides for themes, the API and more
  - name: ğŸ‘®â€â™‚ï¸ Security issue disclosure (SECURITY.md)
    url: https://github.com/OperationCaribbeanSummer/.github/security
    about: Report a security issue in WikiAgora
  - name: ğŸ™‹â€â™€ï¸ Support Request (CONTRIBUTING.md)
    url: https://github.com/OperationCaribbeanSummer/.github/blob/main/CONTRIBUTING.md
    about: Questions and requests for support
